#define SMGR_IDD 45000
#define SMGRHUD_IDD (SMGR_IDD - 1)

#define SMGR_IDC_TOOLBAR  (SMGR_IDD + 1)
#define SMGR_IDC_ACTION_0 (SMGR_IDD + 2)
#define SMGR_IDC_ACTION_1 (SMGR_IDD + 3)
#define SMGR_IDC_ACTION_2 (SMGR_IDD + 4)
#define SMGR_IDC_ACTION_3 (SMGR_IDD + 5)

#define SMGR_IDC_POWER (SMGR_IDD + 6)

#define SMGR_IDC_BOOT_SCREEN 	(SMGR_IDD + 7)
#define SMGR_IDC_PROGRESS_CTRL 	(SMGR_IDD + 8)

#define SMGR_IDC_EDITSETTING		(SMGR_IDD + 9)
#define SMGR_IDC_EDITSETTING_LIST	(SMGR_IDD + 10)

#define SMGR_IDC_MAINMENU		(SMGR_IDD + 11)
#define SMGR_IDC_MAINMENU_LIST 	(SMGR_IDD + 12)

#define SMGR_IDC_SETTINGS		(SMGR_IDD + 13)
#define SMGR_IDC_SETINGS_LIST	(SMGR_IDD + 14)

#define SMGR_IDC_WALLPAPER (SMGR_IDD + 15)

#define SMGR_IDC_INFOBAR		(SMGR_IDD + 16)
#define SMGR_IDC_INFOBAR_DATE	(SMGR_IDD + 17)
#define SMGR_IDC_INFOBAR_TIME 	(SMGR_IDD + 18)
#define SMGR_IDC_INFOBAR_TRK 	(SMGR_IDD + 19)
#define SMGR_IDC_INFOBAR_AUTO 	(SMGR_IDD + 20)
#define SMGR_IDC_INFOBAR_BATT 	(SMGR_IDD + 21)

#define SMGR_IDC_PROGRESS_TEXT (SMGR_IDD + 22)

#define SMGR_IDC_STATUS (SMGR_IDD + 23)
#define SMGR_IDC_STATUS_POWER (SMGR_IDD + 24)

#define SMGR_IDC_F4 (SMGR_IDD + 25)
#define SMGR_IDC_F3 (SMGR_IDD + 26)
#define SMGR_IDC_F1 (SMGR_IDD + 27)

#define SMGR_IDC_NAVIGATION			(SMGR_IDD + 28)
#define SMGR_IDC_NAVIGATION_POS		(SMGR_IDD + 29)
#define SMGR_IDC_NAVIGATION_STR		(SMGR_IDD + 30)
#define SMGR_IDC_NAVIGATION_ELE		(SMGR_IDD + 31)
#define SMGR_IDC_NAVIGATION_MODE	(SMGR_IDD + 32)
#define SMGR_IDC_NAVIGATION_FOM		(SMGR_IDD + 33)
#define SMGR_IDC_NAVIGATION_WP		(SMGR_IDD + 34)
#define SMGR_IDC_NAVIGATION_WPAZ	(SMGR_IDD + 35)
#define SMGR_IDC_NAVIGATION_WPDIST	(SMGR_IDD + 36)

#define SMGR_IDC_WPLIST 		(SMGR_IDD + 37)
#define SMGR_IDC_WPLIST_LIST	(SMGR_IDD + 38)

#define SMGR_IDC_EDITWP			(SMGR_IDD + 39)
#define SMGR_IDC_EDITWP_NAME	(SMGR_IDD + 40)
#define SMGR_IDC_EDITWP_POS		(SMGR_IDD + 41)
#define SMGR_IDC_EDITWP_AZ		(SMGR_IDD + 42)
#define SMGR_IDC_EDITWP_DIST	(SMGR_IDD + 43)
#define SMGR_IDC_EDITWP_TITLE	(SMGR_IDD + 44)

#define SMGR_IDC_POPUP 			(SMGR_IDD + 45)
#define SMGR_IDC_POPUP_TEXT		(SMGR_IDD + 46)

#define SMGR_IDC_DATALINK		(SMGR_IDD + 47)
#define SMGR_IDC_DATALINK_LIST	(SMGR_IDD + 48)

#define SMGR_IDC_P2PLINK		(SMGR_IDD + 49)
#define SMGR_IDC_P2PLINK_TEXT	(SMGR_IDD + 50)

#define SMGR_IDC_LDLINK			(SMGR_IDD + 51)
#define SMGR_IDC_LDLINK_POS		(SMGR_IDD + 52)
#define SMGR_IDC_LDLINK_AZ		(SMGR_IDD + 53)
#define SMGR_IDC_LDLINK_ELE		(SMGR_IDD + 54)
#define SMGR_IDC_LDLINK_DIST	(SMGR_IDD + 55)
#define SMGR_IDC_LDLINK_STATUS	(SMGR_IDD + 56)

#define SMGR_IDC_BACKGROUND		(SMGR_IDD + 57)

#define SMGR_IDC_MAINCONTROLGROUP	(SMGR_IDD + 58)